//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restoran
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservations
    {
        public int ReservationsID { get; set; }
        public string FIO { get; set; }
        public Nullable<int> TableID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> NumberOfPeople { get; set; }
    
        public virtual Tables Tables { get; set; }
        public virtual User User { get; set; }
    }
}
